### ISSUE TITLE
Make easier to run headless

### ISSUE THREAD

**Issue by keiranmraine** [ferrannadeu/indelsClassification#1]
Hi,

It would be good to remove the definition of the image type from the main code and update the example usage to something like:

```
# set display method
pdf(NULL)
# OR write to file
# file=paste0('/path/to/my/output/image.pdf'), width = 12, height = 4

# run the function
out <- indelsClassification(mat = INDELS)
while (!is.null(dev.list()))  dev.off()
```

This makes it easier to run this as an Rscript and generate to different locations.

**Comment by ferrannadeu** [comment]
Thank you for your suggestion!! I have modified the main code and example usage accordingly.
